### ISSUE TITLE
Add functionality inside worker client

### ISSUE THREAD

**Issue by h4n0** [litentry/worker#11]
The worker cli should be able to create an account linker extrinsic and send it to the node. All private information in this extrinsic should be encrypted with the enclave shielding key.

**Comment by haerdib** [comment]
I think for starters we can more or less copy paste the shielding-extrinsic process.
Here's what's done in the worker cli:

1) a cmd is added, that can be called via command line by the user:
 https://github.com/integritee-network/worker/blob/c581f180c8dcac5dafc1337c2d05a806cc6eea2e/cli/src/main.rs#L334-L337
2) then the [chain_api](https://github.com/integritee-network/worker/blob/c581f180c8dcac5dafc1337c2d05a806cc6eea2e/cli/src/main.rs#L368) is retrieved Our worker talks with the node via the [substrate-api-client](https://github.com/scs/substrate-api-client), that, simplified, translates the extrinsic into a json-rpc call and talks to the RPC interface of the node. The node-port that the api is talking to needs to added with a `-p xxxxx` argument, otherwise default port 9944 will be taken.
3) In the [following lines](https://github.com/integritee-network/worker/blob/c581f180c8dcac5dafc1337c2d05a806cc6eea2e/cli/src/main.rs#L369-L400) the command line input arguments are retrieved. For the shielding call only the [recipient account is encrypted](https://github.com/integritee-network/worker/blob/c581f180c8dcac5dafc1337c2d05a806cc6eea2e/cli/src/main.rs#L397-L400). For the linker pallet, we should probably create a wrapper struct that includs all necessary information, and encrypt & sign this struct.  For example: 
```rust
pub struct PrivateLinkerInformation {
    LitentryAccount,
    index,
    addr_expected,
}

```
4) For composing the extrinsic, we need to make sure that the correct [pallet number](https://github.com/integritee-network/worker/blob/c581f180c8dcac5dafc1337c2d05a806cc6eea2e/cli/src/main.rs#L404) is chosen. A simpler example for composing a ballance transfer extrinsic can be found here: https://github.com/scs/substrate-api-client/blob/master/src/examples/example_generic_extrinsic.rs


I think that's all we need for now. Please note that the shielding key for the encryption is retrieved by calling the worker-rpc-interface directly. For this, the client needs to know the worker url it can call. 
If we want to have the cli completely independent on the worker url, we will need to think of a different way how the cli can retrieve the shielding key of the enclave.

An example cli call for a shielding call: 
`./integritee-cli -p 9944 -P 2044 shield-funds //Alice //AliceIcognito 10000 9GSUY4WM3Yim5337AKweJN5Kb9K4yHjFmToLpNccwu7L`
where 
```
 -P <WORKERPORT> the user client can talk to
 -p <NODEPORT> the node is listening on
```

**Comment by haerdib** [comment]
I'm sorry, I was too focused on the onchain call, so I was not actually thinking about the trusted part. But because we're using encryption & shielding key, we should place this client call in the trusted stf-cli section:
https://github.com/litentry/worker/blob/litentry/app-libs/stf/src/cli.rs

This will be called with the addition of a `trusted` in after the cli call:
`./integritee-cli -p 9944 -P 2044 trusted unshield-funds //Alice 10000 //AliceIcognito --mrenclave 9GSUY4WM3Yim5337AKweJN5Kb9K4yHjFmToLpNccwu7L`

It's a little bit intransparent, but we did it to clearly distinct between "open" and "encrypted stf" calls. 
In the stf cli we create a [TrustedOperation](https://github.com/litentry/worker/blob/litentry/app-libs/stf/src/cli.rs#L268-L272)
and then call the [`perform_operation`](https://github.com/litentry/worker/blob/litentry/app-libs/stf/src/cli.rs#L273) function, which was given as an input here : https://github.com/litentry/worker/blob/litentry/cli/src/main.rs#L417

So, by calling this function, we return back to the "main" cli, but only to exectute the [`perform_trusted_operation fn`](https://github.com/litentry/worker/blob/litentry/cli/src/main.rs#L438-L445).

The encryption is happening in the [send_request](https://github.com/litentry/worker/blob/litentry/cli/src/main.rs#L514) function, as well as the sending part.

**Comment by haerdib** [comment]
Also important to know (not for this issue, but in general how the client encryption works): 

The shielding key, used by the client to encrypt the message, is requested here: https://github.com/litentry/worker/blob/litentry/cli/src/main.rs#L501-L504

It is a rpc call directly to the specified worker url. Leaving out a few intermediate steps (let me know if you'd like more details) the call ends up in the enclave-runtime: https://github.com/litentry/worker/blob/litentry/enclave-runtime/src/rpc/worker_api_direct.rs#L217-L240, which returns the public shielding key.

That's why it is necessary to specify a worker url, even though the call is actually sent to the node. If that's an absolute no-go, I think we also have the option to store pub keys onchain, visible to everyone.
