### ISSUE TITLE
Documentation for SGX side-chain architecture

### ISSUE THREAD

**Issue by suinuj** [litentry/worker#15]
**Description**
 Documentation for SGX side-chain architecture, write a doc to describe the Integritee's SGX solution and how to use it to implement data privacy in Litentry chain.

**Acceptance Criteria**
- Document in Notion.

**Comment by haerdib** [comment]
Re-posting some of my code links & explanation here:

We have not yet an "official" overall diagramm but in these PR's you can find the main architecture overview:
 Ocall Bridge: https://github.com/integritee-network/worker/pull/293
https://github.com/integritee-network/worker/pull/299
 
Encalve ecalls / ocalls: https://github.com/integritee-network/worker/issues/279
 
Abstract ecalls in enclave : https://github.com/integritee-network/worker/issues/286
Abstract ocalls in enclave :  https://github.com/integritee-network/worker/issues/279
Here's a little outdated description of our sidechain functionality: 
https://polkadot.polkassembly.io/post/111

Here's a simplified sidechain sequence, of a user call and the STF. 
https://raw.githubusercontent.com/haerdib/substraTEE_diagramms/main/sidechain-sequence.svg

And if you ever (which I hope is not the case) need to understand what's happening inside the top_pool:
https://raw.githubusercontent.com/haerdib/substraTEE_diagramms/main/submit_and_watch_sequence.svg

Oh, mabye these will also be able to help: https://github.com/brenzi/substrate-doc, 
not integriTEE specific, but for substrate. Still, because integriTEE incooparetes alot of substrate code, it might be usefule one day.

**Comment by haerdib** [comment]
Small introduction to enclave (including the .edl file construction): https://sgx101.gitbook.io/sgx101/sgx-bootstrap/enclave
Very good edl explainnig section , including example: https://software.intel.com/content/www/us/en/develop/articles/intel-software-guard-extensions-tutorial-part-7-refining-the-enclave.html

**Comment by haerdib** [comment]
Regarding the sgx-runtime functionality: 

The sgx-runtime is called with every execute call , in the [stf_sgx](https://github.com/litentry/worker/blob/litentry/app-libs/stf/src/stf_sgx.rs#L38). This ext variable is type [`State`](https://github.com/litentry/worker/blob/litentry/app-libs/stf/src/stf_sgx.rs#L33), defined in [stf_sgx_primitves](https://github.com/litentry/worker/blob/litentry/app-libs/stf/src/stf_sgx_primitives.rs#L35). But this State time is effecively imported from the sgx-runtime, equalling [`type SgxExternalities:` ](https://github.com/integritee-network/sgx-runtime/blob/master/substrate-sgx/externalities/src/lib.rs#L42-L47).
So whenever this `execute_with` is called, the [sgx-runtime will be used](https://github.com/integritee-network/sgx-runtime/blob/master/substrate-sgx/externalities/src/lib.rs#L104-L110) What follows is a complex - function calling jungle, but it effectively executes the function defined in the `execute_with` function in the stf, but affecting the `SgxExternalities` defined in the sgx-runtime.
This `SgxExternalities` struct is nothing but a wrapper around a [HashMap](https://github.com/integritee-network/sgx-runtime/blob/master/substrate-sgx/externalities/src/lib.rs#L36), offering basic insert and remove functions. The [SgxExternalitiesType](https://github.com/integritee-network/sgx-runtime/blob/master/substrate-sgx/externalities/src/lib.rs#L36) is the effective, permanent state which is encrypted & stored in the bin folder of the worker,
The [`SgxExternalitiesDiffType`](https://github.com/integritee-network/sgx-runtime/blob/master/substrate-sgx/externalities/src/lib.rs#L40) was introduced to store a "state diff", which will be used to by the sidechain of the workers: Because we trust enclaves, we do not want to re-execute all extriniscs, but we can just import the diff to our own state for each block produced by a different enclave.

**Comment by haerdib** [comment]
The `produce_block` main function in the enclave I was talking in our call about, already changed name: it is now called [`sync_parentchain_and_execute_tops_int`](https://github.com/litentry/worker/blob/litentry/enclave-runtime/src/lib.rs#L456) in the function `sync_blocks_on_light_client` the parentchain blocks are iterated through (extrinsic for extrinsc) https://github.com/litentry/worker/blob/litentry/enclave-runtime/src/lib.rs#L512 & https://github.com/litentry/worker/blob/litentry/enclave-runtime/src/lib.rs#L534.
Here we will have to add our Linker Pallet for the enclave know that it's a "relevant extrinsic" that should be exectued: https://github.com/litentry/worker/blob/litentry/enclave-runtime/src/lib.rs#L981-L1022

**Comment by suinuj** [comment]
https://www.notion.so/litentry/Integritee-Architecture-1059bbc665d44568b1c5fdf884b3faa0 ready for review now.
